
// Products
export const PRODUCT_LOADING_START ="PRODUCT_LOADING_START";
export const PRODUCT_LOADING_STOP ="PRODUCT_LOADING_STOP";

export const PRODUCT_ADD= "PRODUCT_ADD";
export const PRODUCT_ADD_SUCCESS="PRODUCT_ADD_SUCCESS";
export const PRODUCT_ADD_FAILURE="PRODUCT_ADD_FAILURE";


export const PRODUCT_DELETE="PRODUCT_DELETE";
export const PRODUCT_DELETE_SUCCESS="PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAILURE="PRODUCT_DELETE_FAILURE";

export const PRODUCT_GET= "PRODUCT_GET";
export const PRODUCT_GET_SUCCESS="PRODUCT_GET_SUCCESS";
export const PRODUCT_GET_FAILURE="PRODUCT_GET_FAILURE";


/// Promo Codes

export const PROMO_LOADING_START ="PROMO_LOADING_START";
export const PROMO_LOADING_STOP ="PROMO_LOADING_STOP";

export const PROMO_ADD= "PROMO_ADD";
export const PROMO_ADD_SUCCESS="PROMO_ADD_SUCCESS";
export const PROMO_ADD_FAILURE="PROMO_ADD_FAILURE";

export const PROMO_DELETE="PROMO_DELETE";
export const PROMO_DELETE_SUCCESS="PROMO_DELETE_SUCCESS";
export const PROMO_DELETE_FAILURE="PROMO_DELETE_FAILURE";

export const PROMO_GET= "PROMO_GET";
export const PROMO_GET_SUCCESS="PROMO_GET_SUCCESS";
export const PROMO_GET_FAILURE="PROMO_GET_FAILURE";


// Cart

export const CART_LOADING_START ="CART_LOADING_START";
export const CART_LOADING_STOP ="CART_LOADING_STOP";

export const CART_ADD= "CART_ADD";
export const CART_ADD_SUCCESS="CART_ADD_SUCCESS";
export const CART_ADD_FAILURE="CART_ADD_FAILURE";

export const CART_DELETE="CART_DELETE";
export const CART_DELETE_SUCCESS="CART_DELETE_SUCCESS";
export const CART_DELETE_FAILURE="CART_DELETE_FAILURE";

export const CART_GET= "CART_GET";
export const CART_GET_SUCCESS="CART_GET_SUCCESS";
export const CART_GET_FAILURE="CART_GET_FAILURE";

export const COUPON_APPLY ="COUPON_APPLY";
export const COUPON_APPLY_SUCCESS="COUPON_APPLY_SUCCESS";
export const COUPON_APPLY_FAILURE="COUPON_APPLY_FAILURE";